### ISSUE TITLE
Reproduce the results on SUN-RGBD

### ISSUE THREAD

**Issue by EternityDS** [Haiyang-W/CAGroup3D#6] opened 2023-02-21 15:58 UTC
Hi,

Thanks for your great work! I follow the instruction and try to reproduce the results on SUN-RGBD. But I only get 61.18 mAP0.25 and 45.14 mAP0.5. These numbers seem much lower than the reported numbers. May I ask what I did wrong? I attached my training log here for your reference. Thanks!
[log_train_20230219-210950.txt](https://github.com/Haiyang-W/CAGroup3D/files/10795266/log_train_20230219-210950.txt)

**Comment by Haiyang-W** [comment] 2023-02-22 08:12
> Hi,
> 
> Thanks for your great work! I follow the instruction and try to reproduce the results on SUN-RGBD. But I only get 61.18 mAP0.25 and 45.14 mAP0.5. These numbers seem much lower than the reported numbers. May I ask what I did wrong? I attached my training log here for your reference. Thanks! [log_train_20230219-210950.txt](https://github.com/Haiyang-W/CAGroup3D/files/10795266/log_train_20230219-210950.txt)

You can first retrain the model with 2x8 (batch size 8 per GPU and two GPU cards in total) because I find your training config is 1x8 ? Our log and pretrain-weight will be released as soon as possible. I am also a PKUer and now rushing the some DDLs (ICCV March 9).  If necessary, you can email and  discuss with me in person. Hope that can ease your concerns.

**Comment by EternityDS** [comment] 2023-02-22 15:52
<img width="392" alt="image" src="https://user-images.githubusercontent.com/30534700/220677827-11fd2e4b-f12c-4a22-8739-8346ba6700e1.png">
Thank you all for the quick reply! I used the processed data in the repo link. I can reproduce the result on ScanNet but get trouble on SUN RGB-D. I tried another experiment with 16x1 batch size and I attached my log here. I will try 8x2 soon. 


"If necessary, you can email and discuss with me in person."
--- That would be great! Can I get your email?

**Comment by Haiyang-W** [comment] 2023-02-23 02:54
> <img alt="image" width="392" src="https://user-images.githubusercontent.com/30534700/220677827-11fd2e4b-f12c-4a22-8739-8346ba6700e1.png">
> 
> Thank you all for the quick reply! I used the processed data in the repo link. I can reproduce the result on ScanNet but get trouble on SUN RGB-D. I tried another experiment with 16x1 batch size and I attached my log here. I will try 8x2 soon.
> "If necessary, you can email and discuss with me in person." --- That would be great! Can I get your email?

My email is "wanghaiyang6@stu.pku.edu.cn". If you have any questions, please feel free to contact me. :)

Best regards,
Haiyang

**Closed** 2023-03-04 11:43 UTC

**Comment by Haiyang-W** [comment] 2023-03-08 16:55
> <img alt="image" width="392" src="https://user-images.githubusercontent.com/30534700/220677827-11fd2e4b-f12c-4a22-8739-8346ba6700e1.png">
> 
> Thank you all for the quick reply! I used the processed data in the repo link. I can reproduce the result on ScanNet but get trouble on SUN RGB-D. I tried another experiment with 16x1 batch size and I attached my log here. I will try 8x2 soon.
> "If necessary, you can email and discuss with me in person." --- That would be great! Can I get your email?
Have you reproduced it on your side? Let me know if you have any questions.  Thanks! :)

**Comment by EternityDS** [comment] 2023-03-09 22:29
Hi,

Really thank you for keep following up! I have reproduced the result with 8x2 batchsize setting but still cannot reproduce with 16x1 or 8x1. I was working on other things and did not look into this issue. Have you tried to reproduce the result with 1 GPU?

**Comment by Haiyang-W** [comment] 2023-03-10 05:09
Hi, 
Sorry for that, I've only tried the 8x2.  In principle, 16x1 should be fine. I'll try this setting later.

Haiyang
